# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f464a2649ffd4222f8db69ae0873bab70b6b368647b6a1f07a1c5b919190626ce7b5b313c6666e3ac05263aed1942d354d2bcfc1eb4a63e45ab0083300d30b6

test:
  secret_key_base: 1b2784888de98354e6040e18929142aa99ee1b3b4b7ba786b8d5885ff687aa1821ed946db71a49ba39c081dd6a7781fbeeec9263a3064a8d14d7c68eaa25219c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
